services:
  react-app:
      container_name: react-app
      stdin_open: true
      build: .
      volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
      expose:
        - 3000
      ports:
        - 3000:3000
      environment:
          - CHOKIDAR_USEPOLLING=true