version: "3"
services:
  db0:
    container_name: mariadb-galera-0
    image: bitnami/mariadb-galera:latest
    restart: unless-stopped
    volumes:
      - ./mariadb_cluster/node0:/bitnami/mariadb \
      - ./mariadb_cluster/node0/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro \
    environment:
      - NODE_NAME=NODE0
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_MARIABACKUP_USER=dev101
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=devbackup101
      - MARIADB_ROOT_USER =root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=devchon
      - MARIADB_PASSWORD=devchon101
      - MARIADB_DATABASE=mymariaDB
    networks:
      - db
    ports:
      - 23300:3306

  db1:
    container_name: mariadb-galera-1
    image: bitnami/mariadb-galera:latest
    restart: unless-stopped
    volumes:
      - ./mariadb_cluster/node1:/bitnami/mariadb \
      - ./mariadb_cluster/node1/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro \
    environment:
      - NODE_NAME=NODE0
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera \
      #- MARIADB_ROOT_PASSWORD=root
      - MARIADB_GALERA_MARIABACKUP_USER=dev101
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=devbackup101
    networks:
      - db
    ports:
      - 23301:3306
    links:
      - db0:db1
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  db:
    driver: bridge